## FundaML 1: Làm việc với mảng một chiều

##### 1.1 Khởi tạo mảng 1 chiều

In [5]:
import numpy as np
X = np.array([1,2,3,4,5,6,7,8,9,10])
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### 1.3. Khởi tạo các mảng một chiều đặc biệt




In [6]:
#Bai tap 1
Y = np.arange(2**0,2**10)
Y

array([   1,    2,    3, ..., 1021, 1022, 1023])

In [7]:
#Bai tap 2
X = np.array([3,3,3,3,3,3,3,3,3,1.5])
X

array([3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 1.5])

#### 1.4. Truy cập mảng một chiều


In [8]:
X = np.array([1,2,3])

for X2 in X:
    X2 = np.mean(X)
X[0] = X2
X[1] = X2
X[2] = X2
X

array([2, 2, 2])

### 1.5. Truy cập nhiều phần tử của mảng một chiều

In [21]:
n = np.array([0,2,4,6,8,10,12,14])
n = np.arange(2,-)
n

array([ 2. ,  1.5,  1. ,  0.5,  0. , -0.5])

In [40]:
import numpy as np 
a = np.arange(2) 
s = slice(2,9,1) 
a[s]

array([2, 3])