## FundaML 1: Làm việc với mảng một chiều

##### 1.1 Khởi tạo mảng 1 chiều

In [1]:
import numpy as np
X = np.array([1,2,3,4,5,6,7,8,9,10])
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### 1.3. Khởi tạo các mảng một chiều đặc biệt




In [2]:
#Bai tap 1
Y = np.arange(2**0,2**10)
Y

array([   1,    2,    3, ..., 1021, 1022, 1023])

In [3]:
#Bai tap 2
X = np.array([3,3,3,3,3,3,3,3,3,1.5])
X

array([3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 1.5])

#### 1.4. Truy cập mảng một chiều


In [4]:
X = np.array([1,2,3])

for X2 in X:
    X2 = np.mean(X)
X[0] = X2
X[1] = X2
X[2] = X2
X

array([2, 2, 2])

### 1.5. Truy cập nhiều phần tử của mảng một chiều

In [5]:
n = np.array([0,2,4,6,8,10,12,14])
n = np.arange(2)
n

array([0, 1])

In [6]:
import numpy as np 
a = 5

a = np.linspace(2)
a

TypeError: linspace() missing 1 required positional argument: 'stop'

In [ ]:
a = np.arange(2,1,-0.5)
np.linspace(,5,5)

### 1.6

In [ ]:
X = np.array([1,2,3,4])
pi = 3.14

Y = pi/2 - X
print("Y = ",Y)



z = np.cos(X) - np.sin(X)
print('z = ', z)

print('\nTong cua z =',np.sum(z))


### 1.7


In [7]:
X = [-11,5212,-243,124]
Y = np.abs(X)
print (Y)
print ('\ntong tri tuyet doi = ', np.sum(Y))

[  11 5212  243  124]

tong tri tuyet doi =  5590


### 1.8

In [19]:
z = np.array([3,6,1,9])
j = 0
while j<10:
    exp_z = np.exp(z)*j
    j = j+1
print(exp_z)
#############################
print(np.exp(z))
A = np.exp(z)/exp_z
A



[1.80769832e+02 3.63085914e+03 2.44645365e+01 7.29277553e+04]
[2.00855369e+01 4.03428793e+02 2.71828183e+00 8.10308393e+03]


array([0.11111111, 0.11111111, 0.11111111, 0.11111111])

### 1.9

In [11]:
X = [1,2,3,4,5,6]
np.dot(X,X)

91